### ISSUE TITLE
Greeks - Are they relevant? 

### ISSUE THREAD

**Issue by andrewcz** [Jordylek/VolatilityIsMostlyPathDependent#2]
Hi @JulienGuyon @Jordylek 

Thank you for releasing the code.

I just wondering for delta hedging strategies, it is required to differentiate to get the Greeks.

Are you able to do this with this algorithm?

If so where would that be in the code.

Cheers,
Andrew

**Comment by Jordylek** [comment]
I think the only way to do it now is to run multiple simulations to approximates the derivates.

Regards,
Jordan

**Comment by andrewcz** [comment]
Thank you @Jordylek would these be calculations that could be added to the repository.

Cheers and thanks,
Andrew

**Comment by Jordylek** [comment]
I do not think so. It is not a priority for us at the moment.
