### ISSUE TITLE
Parabolic term not correctly implemented in the code?

### ISSUE THREAD

**Issue by Sinbad-The-Sailor** [Jordylek/VolatilityIsMostlyPathDependent#3]
Looking at the parabolic term, the added term for OTM call options, it seems as if it is implemented as the indicator times $R_1$ and not $R_1$ squared as shown in the article.

vol = self.betas[0] + self.betas[1] * R_1 + self.betas[2] * torch.sqrt(R_2) + self.parabolic * (R_1 - self.parabolic_offset).clamp(min=0) * 2

Is this correct, or is this an old version of the code?

**Comment by Jordylek** [comment]
Thank you for noticing it. It is a typo in this version of the code. I will update it.
